### ISSUE TITLE
I can no longer use custom `args` with the main hook

### ISSUE THREAD

**Issue by Jayman2000** [scop/pre-commit-shfmt#19]
I want to use shfmt’s `--func-next-line` option with one of these hooks. My pre-commit config used to look like this:

```yaml
    -
        repo: https://github.com/scop/pre-commit-shfmt
        rev: v3.7.0-1
        hooks:
            -
                id: shfmt
                args: ["-fn"]
```

Once I updated to v3.7.0-2, it started giving me these errors:

```
shfmt....................................................................Failed
- hook id: shfmt
- exit code: 2

flag provided but not defined: -fn
Usage of /home/jayman/.cache/pre-commit/repoqk0av65h/py_env-python3.11/bin/wrun:
  -http-timeout duration
        HTTP client timeout (default 5m0s)
  -url value
        [<OS>/<architecture>=]URL (at least one required to match)
wrun: ERROR: parse flags: flag provided but not defined: -fn
flag provided but not defined: -fn
Usage of /home/jayman/.cache/pre-commit/repoqk0av65h/py_env-python3.11/bin/wrun:
  -http-timeout duration
        HTTP client timeout (default 5m0s)
  -url value
        [<OS>/<architecture>=]URL (at least one required to match)
wrun: ERROR: parse flags: flag provided but not defined: -fn

```

I think that this is a result of 286f22a (feat: use prebuilt upstream exe in `shfmt`, src install in `shfmt-src`, 2023-11-13). I was able to work around this issue by switching to the `shfmt-docker` hook.
